
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int FLOAT_LIT = 4;
  public static final int PLUSPLUS = 42;
  public static final int CHAR_LIT = 5;
  public static final int LBRACKET = 28;
  public static final int MULT = 36;
  public static final int CHAR = 10;
  public static final int GE = 45;
  public static final int UCOMP = 52;
  public static final int UMINUS = 50;
  public static final int UPLUS = 51;
  public static final int LPAREN = 24;
  public static final int INT = 9;
  public static final int MINUS = 35;
  public static final int TILDE = 41;
  public static final int RPAREN = 25;
  public static final int AND = 48;
  public static final int SEMICOLON = 30;
  public static final int LT = 39;
  public static final int OR = 49;
  public static final int BOOL = 11;
  public static final int COMMA = 31;
  public static final int CLASS = 7;
  public static final int DIV = 37;
  public static final int PLUS = 34;
  public static final int ASSIGN = 38;
  public static final int IF = 15;
  public static final int ID = 2;
  public static final int LE = 44;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 43;
  public static final int RETURN = 18;
  public static final int RBRACKET = 29;
  public static final int PRINTLINE = 21;
  public static final int TRUE = 22;
  public static final int error = 1;
  public static final int VOID = 8;
  public static final int EQ = 46;
  public static final int COLON = 32;
  public static final int LBRACE = 26;
  public static final int ELSE = 16;
  public static final int UCAST = 53;
  public static final int READ = 19;
  public static final int FINAL = 14;
  public static final int WHILE = 17;
  public static final int FLOAT = 12;
  public static final int RBRACE = 27;
  public static final int NE = 47;
  public static final int STRING = 13;
  public static final int QUESTION = 33;
  public static final int FALSE = 23;
  public static final int STRING_LIT = 6;
  public static final int GT = 40;
  public static final int INT_LIT = 3;
  public static final int PRINT = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "INT_LIT",
  "FLOAT_LIT",
  "CHAR_LIT",
  "STRING_LIT",
  "CLASS",
  "VOID",
  "INT",
  "CHAR",
  "BOOL",
  "FLOAT",
  "STRING",
  "FINAL",
  "IF",
  "ELSE",
  "WHILE",
  "RETURN",
  "READ",
  "PRINT",
  "PRINTLINE",
  "TRUE",
  "FALSE",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "LBRACKET",
  "RBRACKET",
  "SEMICOLON",
  "COMMA",
  "COLON",
  "QUESTION",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "ASSIGN",
  "LT",
  "GT",
  "TILDE",
  "PLUSPLUS",
  "MINUSMINUS",
  "LE",
  "GE",
  "EQ",
  "NE",
  "AND",
  "OR",
  "UMINUS",
  "UPLUS",
  "UCOMP",
  "UCAST"
  };
}

